Traceback (most recent call last):
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/user/.edm/envs/mdd/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
y = array([10.02, 10.20, 10.26, 10.20, 10.22, 10.13, 9.97, 10.12, 10.09, 9.90, \
     10.05, 10.17, 10.42, 10.21, 10.23, 10.11, 9.98, 10.10, 10.04, 9.81])

figure(figsize=(8,4))
plot(y,'o',markersize=10)
plot(y.mean()*ones(size(P)),'r--',lw=2)
plot(10*ones(size(y)),'k-',lw=2)
text(6.,y.mean()+.05,'Average',fontsize=14,color='r')
text(5.,10.01,'True',fontsize=14)
xlabel('trial')
ylabel(r'$P$ [kPa]') 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [2], line 6[0m
[1;32m      4[0m figure(figsize[38;5;241m=[39m([38;5;241m8[39m,[38;5;241m4[39m))
[1;32m      5[0m plot(y,[38;5;124m'[39m[38;5;124mo[39m[38;5;124m'[39m,markersize[38;5;241m=[39m[38;5;241m10[39m)
[0;32m----> 6[0m plot(y[38;5;241m.[39mmean()[38;5;241m*[39mones(size([43mP[49m)),[38;5;124m'[39m[38;5;124mr--[39m[38;5;124m'[39m,lw[38;5;241m=[39m[38;5;241m2[39m)
[1;32m      7[0m plot([38;5;241m10[39m[38;5;241m*[39mones(size(y)),[38;5;124m'[39m[38;5;124mk-[39m[38;5;124m'[39m,lw[38;5;241m=[39m[38;5;241m2[39m)
[1;32m      8[0m text([38;5;241m6.[39m,y[38;5;241m.[39mmean()[38;5;241m+[39m[38;5;241m.05[39m,[38;5;124m'[39m[38;5;124mAverage[39m[38;5;124m'[39m,fontsize[38;5;241m=[39m[38;5;241m14[39m,color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'P' is not defined
NameError: name 'P' is not defined

